name: Build WPF App

on:
  push:
    branches: [ PolishRacer ]
  pull_request:
    branches: [ PolishRacer ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      run: nuget restore WpfApp1.sln

    - name: Build solution
      run: msbuild WpfApp1.sln /p:Configuration=Release

    - name: Run tests
      run: dotnet test WpfApp1.Tests/WpfApp1.Tests.csproj

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PolishRacer Build
        path: WpfApp1/bin/Release/
